<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="wonders_of_the_world.xsl"?>
<!DOCTYPE catalog [
	<!NOTATION jpg SYSTEM "image/jpeg">
	<!ENTITY statue_of_christ_the_redeemer1 SYSTEM "images/new_wonders/statue_of_christ_the_redeemer1.jpg" NDATA jpg>
	<!ENTITY great_wall_of_china1 SYSTEM "images/new_wonders/great_wall_of_china1.jpg" NDATA jpg>
	<!ENTITY petra1 SYSTEM "images/new_wonders/petra1.jpg" NDATA jpg>
	<!ENTITY chichen_itza1 SYSTEM "images/new_wonders/chichen_itza1.jpg" NDATA jpg>
	<!ENTITY machu_picchu1 SYSTEM "images/new_wonders/machu_picchu1.jpg" NDATA jpg>
	<!ENTITY taj_mahal1 SYSTEM "images/new_wonders/taj_mahal1.jpg" NDATA jpg>
	<!ENTITY colosseum1 SYSTEM "images/new_wonders/colosseum1.jpg" NDATA jpg>
	
	<!ENTITY grand_canyon1 SYSTEM "images/natural_wonders/grand_canyon1.jpg" NDATA jpg>
	<!ENTITY northern_lights1 SYSTEM "images/natural_wonders/northern_lights1.jpg" NDATA jpg>
	<!ENTITY mount_everest1 SYSTEM "images/natural_wonders/mount_everest1.jpg" NDATA jpg>
	<!ENTITY paricutin1 SYSTEM "images/natural_wonders/paricutin1.jpg" NDATA jpg>
	<!ENTITY harbour_of_rio_de_janeiro1 SYSTEM "images/natural_wonders/harbour_of_rio_de_janeiro1.jpg" NDATA jpg>
	<!ENTITY victoria_falls1 SYSTEM "images/natural_wonders/victoria_falls1.jpg" NDATA jpg>
	<!ENTITY great_barrier_reef1 SYSTEM "images/natural_wonders/great_barrier_reef1.jpg" NDATA jpg>
	
	<!ENTITY hanging_gardens_of_babylon1 SYSTEM "images/old_wonders/hanging_gardens_of_babylon1.jpg" NDATA jpg>
	<!ENTITY statue_of_zeus_at_olympia1 SYSTEM "images/old_wonders/statue_of_zeus_at_olympia1.jpg" NDATA jpg>
	<!ENTITY colossus_of_rhodes1 SYSTEM "images/old_wonders/colossus_of_rhodes1.jpg" NDATA jpg>
	<!ENTITY temple_of_artemis1 SYSTEM "images/old_wonders/temple_of_artemis1.jpg" NDATA jpg>
	<!ENTITY mausoleum_at_halicarnassus1 SYSTEM "images/old_wonders/mausoleum_at_halicarnassus1.jpg" NDATA jpg>
	<!ENTITY lighthouse_of_alexandria1 SYSTEM "images/old_wonders/lighthouse_of_alexandria1.jpg" NDATA jpg>
	<!ENTITY pyramid_giza1 SYSTEM "images/old_wonders/pyramid_giza1.jpg" NDATA jpg>
	<!ELEMENT catalog (continents, types_of_wonders, wonders)>
	<!ELEMENT continents (continent_selector+)>
	<!ELEMENT types_of_wonders (type_of_wonder+)>
	<!ELEMENT wonders (wonder+)>
	<!ELEMENT continent_selector (continent_name)>
	<!ELEMENT type_of_wonder (type_of_wonder_name)>
	<!ELEMENT continent_name (#PCDATA)>
	<!ELEMENT type_of_wonder_name (#PCDATA)>
	<!ELEMENT wonder (name, nickname?, destination, history, description, accessibility, related_landmarks, images)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT nickname (#PCDATA)>
	<!ELEMENT destination (continent?, country?, region?, state?, city?, place?, cont-id, type-id)>
	<!ELEMENT history (creation,  changes)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT accessibility (transport, worktime, ticket_price)>
	<!ELEMENT related_landmarks (landmark*)>
	<!ELEMENT images (image+)>
	<!ELEMENT continent (#PCDATA)>
	<!ELEMENT region (#PCDATA)>
	<!ELEMENT country (#PCDATA)>
	<!ELEMENT city (#PCDATA)>
	<!ELEMENT place (#PCDATA)>
	<!ELEMENT cont-id (#PCDATA)>
	<!ELEMENT type-id (#PCDATA)>
	<!ELEMENT state (#PCDATA)>
	<!ELEMENT creation (#PCDATA)>
	<!ELEMENT changes (#PCDATA)>
	<!ELEMENT transport (#PCDATA)>
	<!ELEMENT worktime (#PCDATA)>
	<!ELEMENT ticket_price (#PCDATA)>
	<!ELEMENT landmark (#PCDATA)>
	<!ELEMENT image (image_src)>
	<!ELEMENT image_src (#PCDATA)>
	<!ATTLIST catalog xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance">
	<!ATTLIST catalog xsi:noNamespaceSchemaLocation CDATA #FIXED "wonders_of_the_world.xsd">
	<!ATTLIST continent_selector continentID ID #REQUIRED>
	<!ATTLIST continent_selector wonderRef1 IDREFS #IMPLIED>
	<!ATTLIST type_of_wonder type_of_wonder_ID ID #REQUIRED>
	<!ATTLIST type_of_wonder wonderRef2 IDREFS #IMPLIED>
	<!ATTLIST wonder wonderId ID #REQUIRED>
	<!ATTLIST image type NMTOKEN #REQUIRED>
	<!ATTLIST image_src href CDATA #REQUIRED>
	<!ATTLIST image_src ent ENTITY #REQUIRED>
]>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:noNamespaceSchemaLocation="wonders_of_the_world.xsd">

	<!--==========================Regions=================================-->

    <continents>
        <continent_selector continentID = "AS" wonderRef1="PETRA GREAT_WALL TAJ_MAHAL EVEREST HANGING_GARDENS_OF_BABYLON TEMPLE_OF_ARTEMIS_AT_EPHESUS">
            <continent_name>Азия</continent_name>
        </continent_selector>
        
        <continent_selector continentID = "AU" wonderRef1="GREAT_BARRIER_REEF">
            <continent_name>Австралия</continent_name>
        </continent_selector>
        
        <continent_selector continentID = "EU" wonderRef1="COLLOSEUM STATUE_OF_ZEUS_AT_OLYMPIA COLOSSUS_OF_RHODES MAUSOLEUM_AT_HALICARNASSUS">
            <continent_name>Европа</continent_name>
        </continent_selector>
        
        <continent_selector continentID = "SA" wonderRef1="CHICHEN_ITZA STATUE_CHRIST MACHU_PICCHU RIO_DE_JANEIRO_HARBOUR">
            <continent_name>Южна Америка</continent_name>
        </continent_selector>
        
        <continent_selector continentID = "NA" wonderRef1="GRAND_CANYON PARICUTIN">
            <continent_name>Северна Америка</continent_name>
        </continent_selector>
        
        <continent_selector continentID = "AF" wonderRef1="VICTORIA_FALLS GREAT_PYRAMID_OF_GIZA LIGHTHOUSE_OF_ALEXANDRIA">
            <continent_name>Африка</continent_name>
        </continent_selector>
        
        <continent_selector continentID = "AN" wonderRef1="AURORA">
            <continent_name>Антрактида</continent_name>
        </continent_selector>
    </continents>
    

	<!--======================Types=======================-->

	<types_of_wonders>
        <type_of_wonder type_of_wonder_ID = "OW" wonderRef2="HANGING_GARDENS_OF_BABYLON STATUE_OF_ZEUS_AT_OLYMPIA TEMPLE_OF_ARTEMIS_AT_EPHESUS MAUSOLEUM_AT_HALICARNASSUS 
															LIGHTHOUSE_OF_ALEXANDRIA COLOSSUS_OF_RHODES GREAT_PYRAMID_OF_GIZA">
            <type_of_wonder_name>Стари чудеса на света</type_of_wonder_name>
        </type_of_wonder>
        
        <type_of_wonder type_of_wonder_ID = "NW" wonderRef2="STATUE_CHRIST GREAT_WALL PETRA CHICHEN_ITZA MACHU_PICCHU TAJ_MAHAL COLLOSEUM">
            <type_of_wonder_name>Нови чудеса на света</type_of_wonder_name>
        </type_of_wonder>

		<type_of_wonder type_of_wonder_ID = "NAW" wonderRef2="GRAND_CANYON AURORA EVEREST PARICUTIN RIO_DE_JANEIRO_HARBOUR VICTORIA_FALLS GREAT_BARRIER_REEF ">
            <type_of_wonder_name>Природни чудеса</type_of_wonder_name>
        </type_of_wonder>
    </types_of_wonders>

  	<wonders>
	
	<!-- Новите чудеса на света -->

		<wonder wonderId="STATUE_CHRIST">
			<name>Статуята на Исус Христос Спасителя</name>
			<destination>
				<continent>Южна Америка</continent>
				<country>Бразилия</country>
				<city>Рио де Жанейро</city>
				<place>хълм Корковадо</place>
				<cont-id>SA</cont-id>
				<type-id>NW</type-id>
			</destination>
			<history>
				<creation>
				Предложението за построяването на християнски монумент на връх Коровадо в Рио де Жанейро, в чест на принцеса Изабел, датира от средата на 50-те години на XIX в. 
				Идеите за това как да изглежда статуята варират, като сред тях присъства такава, в която Исус държи земното кълбо в ръката си. 
				Въпреки множеството дизайни, които са изпратени за одобрение, комисията финално избира именно този архитектурен проект, който познаваме днес.
				</creation>
				<changes>
				За да се отбележи 75-годишнината от построяването на статуята, в основата ѝ бива построен параклис през 2006 г. 
				Към днешна дата той се посещава от милиони туристи годишно.
				</changes>
			</history>
			<description>
			Статуята на Христос е с разперени ръце и гледа към Рио де Жанейро.
			Завършена през 1931 г., тя е висока 38 м, изградена е от стоманобетон и е облицована с несмлян талк, устойчив на въздействието на климата.
			Статуята е разположена на високия 710 м хълм Корковаду в предградията на града. 
			Допълнителната височина на хълма превръща този съвременен колос в емблематична забележителност на града.
			</description>
			<accessibility>
				<transport>
				Качването отнема около 20 минути. 
				Влакът превозва пътници на всеки 20-30 минути от начална гарата от 8:20 ч. до 17 ч. всеки ден, а последният курс в обратна посока е между 18:30 ч. и 19 ч.
				</transport>
				<worktime>8:00-19:00</worktime>
				<ticket_price>
				Деца под 4 - безплатно
				Деца от 5 до 11 - 24лв
				Възрастни - 37лв
				Пенсионери - 12лв
				</ticket_price>
			</accessibility>
			<related_landmarks> 
				<landmark>
				Пристанището на Рио де Жанейро - място, където се срещат историята, културата и природата. 
				Тук можете да видите следите от колониалното, имперското и републиканското минало на града, изразени в архитектурата, паметниците и музеите,
				да се докоснете до духа на карнавала, самбата и боса новата, които са символи на радостта, музиката и танца.
				</landmark>
				<landmark>
				Уруапан - това е най-близкият град до Парикутин и е известен като “столицата на авокадото”. Тук можете да посетите националния парк “Едуардо Руис”, 
				където ще видите впечатляващи водопади, тропически гори и разнообразни растения и животни. 
				Също така, можете да опитате някои от местните специалитети, като авокадово морожено, авокадова супа или авокадова пица.
				</landmark>
				<landmark>
				Патцкуаро - това е колониален град, който се намира на около 60 километра от Парикутин и е известен като “магически град”. 
				Тук можете да се насладите на архитектурата, културата и историята на града, който е бил столица на тарасканското царство. 
				Също така, можете да посетите езерото Патцкуаро, където ще видите плаващи острови, наречени “ханицио”, и да се запознаете с живота на местните рибари и занаятчии.
				</landmark>
			</related_landmarks>
			<images>
				<image type="1">
					<image_src href="images/new_wonders/statue_of_christ_the_redeemer1.jpg" ent="statue_of_christ_the_redeemer1"/>
				</image>
			</images>
		</wonder>

		<wonder wonderId="GREAT_WALL">
			<name>Великата китайска стена</name>
			<nickname>Стената; Стената на дракона; Стена, дълга 10000 ли; Чанчън</nickname>
			<destination>
				<continent>Азия</continent>
				<country>Китай</country>
				<cont-id>AS</cont-id>
				<type-id>NW</type-id>
			</destination>
			<history>
				<creation>
				През VII-V век пр.Хр. много китайски държави започват да строят стени, за да се защитят от номадски нашествия от север.
				През 221-206 година пр.Хр. първият китайски император Цин Шъхуан поставя началото на грандиозен проект за съединяване на
				отделните стени и изграждане на нови, за да се създаде единна отбранителна линия.
				</creation>
				<changes>
				През I-II век династията Хан укрепва и разширява стената, а до XVI век различни династии продължават с поддръжката, но без
				да я разширяват значително. През XVI-XVII век династията Мин е изградила най-модерната и най-дългата версия на стената, за
				да се противопостави на монголската заплаха. Тази стена е била изградена от камък и тухли и е достигала до 8850 км дължина. 
				Тя е имала много наблюдателни кули, казарми, гарнизони и системи за сигнализация. Това е стената, която можем да видим днес.
				</changes>
			</history>
			<description>
			Великата китайска стена е огромно съоръжение, което пресича северната и централната част на Китай. 
			Тя има много различни секции, които са построени в различни периоди от историята. Изградена е 
			от различни материали, като камък, тухли, дърво и пръст, и има много наблюдателни кули, казарми, 
			гарнизони и системи за сигнализация. Символ е на китайската култура, история и изобретателност.
			Бадалинг (Badaling) - това е най-посещаваният и най-добре запазен раздел на стената. 
			Тук можете да видите впечатляващи гледки към стената, която се извива по хълмистата местност.
			Цзиншанлинг (Jinshanling) - това е раздел на стената, който е по-далеч от Пекин и по-трудно достъпен, 
			но предлага по-автентично и по-спокойно изживяване. Тук можете да видите стената в по-оригиналния й вид, 
			с много наблюдателни кули и разрушени части. Това е добро място за пешеходен туризъм и снимки.
			</description>
			<accessibility>
				<transport>
				Бадалинг - намира се на около 90 км северозападно от Пекин и е лесно достъпен с автобус, влак или такси. 
				Цзиншанлинг (Jinshanling) - на около 130 км североизточно от Пекин и е достъпен с автобус или такси.
				</transport>
				<worktime>
				Бадалинг - Работното време на този раздел е от 6:30 до 19:00 часа през лятото и от 7:00 до 18:00 часа през зимата.
				Цзиншанлинг - Работното време на този раздел е от 8:00 до 17:00 часа през цялата година.
				</worktime>
				<ticket_price>
				Бадалинг - Цената на билета е 40 юана за възрастни и 20 юана за деца.
				Цзиншанлинг - Цената на билета е 65 юана за възрастни и 35 юана за деца.
				</ticket_price>
			</accessibility>
			<related_landmarks> 
				<landmark>Няма</landmark>
			</related_landmarks>
			<images>
				<image type="1">
					<image_src href="images/new_wonders/great_wall_of_china1.jpg" ent="great_wall_of_china1"/>
				</image>
			</images>
		</wonder>
	
		<wonder wonderId="PETRA">
			<name>Петра</name>
			<nickname>Розовият град</nickname>
			<destination> 
				<continent>Азия</continent>
				<country>Йордания</country>
				<city>Маан</city>
				<place>Долината на Мойсей</place>
				<cont-id>AS</cont-id>
				<type-id>NW</type-id>
			</destination> 
			<history>
				<creation>
				Петра е основана от набатеите, древно арабско племе, което е известно с изкуството си
				да издълбава скални сгради и да управлява водата в пустинни условия. Петра е била столица
				на набатейското царство и процъфтяващ търговски център, свързващ различни култури и 
				цивилизации.
				</creation>
				<changes>
				Петра е претърпяла много промени в хода на историята. През I век н.е. тя е анексирана от 
				Римската империя и става част от провинция Арабия. През IV век н.е. е включена във
				Византийската империя и става християнски център. През VII век н.е. е завладяна от 
				арабите и постепенно започва да тъне в забвение. През XII век н.е. кръстоносците построили 
				крепост над нея. През XIX век н.е. тя е преоткрита от европейски пътешественици и 
				става обект на изследвания и туризъм.
				</changes>
			</history>
			<description>
			Петра е един от най-впечатляващите и красиви археологически обекти в света. 
			Тя е известна със своите скални сгради, които са издълбани в розови пясъчни 
			скали и имат изящни фасади с колони и орнаменти. Най-известната сграда в Петра 
			е Ел-Хазне, или Съкровищницата, която е служила като гробница или храм. Други 
			забележителности в Петра са театърът, който е побрал до 3000 зрители, монументалният 
			храм Ел-Дейр, или Манастирът, който е разположен на висок хълм, и множество други 
			гробници, храмове, светилища и жилища. Петра е заобиколена от величествени планини,
			които поднасят невероятни пейзажи и атмосфера.
			</description>
			<accessibility>
				<transport>
				Петра се намира на около 240 км от столицата на Йордания Аман и на около 120 км 
				от Червено море. Най-лесният начин да се стигне до нея е с автобус, кола или такси. 
				Входът в Петра е от градчето Уади Муса, където има много хотели, ресторанти и магазини. 
				Оттам до входа на археологическия парк има около 2 км, които могат да се извървят пеша, 
				с кон, с магаре или с количка. За да се влезе в Петра, трябва да се премине през тесния
				и дълъг пролом Сик, който е с дължина около 1,2 км и е широк от 3 до 12 метра. 
				Сик е едно от най-завладяващите места в Петра, тъй като скалите са извити и изрязани от водата 
				и вятъра, а на някои места достигат до 80 метра височина. Отвъд Сик се открива целият разкош 
				на Петра, който може да се разгледа пеша, с кон, с магаре, с камила или с малка количка.
				</transport>
				<worktime>
				Всеки ден от 6:00 до 18:00 часа през лятото и 
				от 6:00 до 16:00 часа през зимата.
				</worktime>
				<ticket_price>
				Входната такса за Петра зависи от продължителността на престоя и от националността на 
				посетителя. За туристи, които пренощуват в Йордания, цената е 50 джод (около 70 долара) 
				за един ден, 55 джод (около 78 долара) за два дни и 60 джод (около 85 долара) за три дни.
				За туристи, които не пренощуват в Йордания, цената е 90 джод (около 127 долара) за един 
				ден. За деца под 12 години входът е безплатен. В цената на билета е включен и безплатен 
				водач, който обяснява историята и културата на Петра на английски или арабски език. 
				Също така, в цената на билета е включена и една безплатна обиколка с кон от входа на 
				парка до началото на Сик, която трае около 15 минути. Обратното пътуване с кон обаче 
				не е безплатно и трябва да се заплати на коновода. За други видове транспорт, като 
				магарета, камили или колички, също трябва да се плати допълнително.
				</ticket_price>
			</accessibility>
			<related_landmarks> 
				<landmark>Няма</landmark>
			</related_landmarks>
			<images>
				<image type="1">
					<image_src href="images/new_wonders/petra1.jpg" ent="petra1"/>
				</image>
			</images>
		</wonder>

		<wonder wonderId="CHICHEN_ITZA">
			<name>Чичен Ица</name>
			<nickname>Градът на магьосниците на водата</nickname>
			<destination>
				<continent>Северна Америка</continent>
				<country>Мексико</country>
				<place>Северен полуостров Юкатан</place>
				<cont-id>NA</cont-id>
				<type-id>NW</type-id>
			</destination>
			<history>
				<creation>
				Чичен Ица е построен между 600 г. пр.н.е. и 800 г. сл.н.е. като политически и културен център на маите, една от най-развитите цивилизации в древна Америка. 
				Името на града означава "В гърлото на кладенеца на Ица", като Ица е етнос, който е доминирал в региона. 
				Градът е бил изграден около две големи карстови кладенци, които са служили за водоснабдяване и за жертвоприношения на бога на дъжда Чаак.
				</creation>
				<changes>
				През X век Чичен Ица е превзет от толтеките, които са внесли нови елементи в архитектурата и изкуството на града. 
				Толтеките са почитали бога Кукулкан, който е изобразен като пернат змей. През XI век Чичен Ица става столица на 
				толтекската държава и един от най-могъщите градове в Средна Америка. През 1178 година градът е разрушен от обединената
				армия на Майяпан, Ушмал и Ицмал, управлявана от Хунак Кел. По времето на испанските завоевания в средата на XVI 
				век Чичен Ица е в развалини.
				</changes>
			</history>
			<description>
			Чичен Ица е пълен с впечатляващи паметници, които отразяват смесицата от майската и толтекската култури. 
			Най-известната сграда е пирамидата на Кукулкан, която е висока 24 метра и има девет стъпала, символизиращи деветте нива на подземния свят. 
			На всяка страна на пирамидата има широко стълбище с 91 стъпала, които заедно с платформата на върха правят общо 365 - броят на дните в майския календар. 
			Два пъти годишно, на равноденствията, сянката на пирамидата създава илюзията за спускащ се змей, който достига до главата на Кукулкан, разположена в основата на стълбището.
			Други забележителности в Чичен Ица са храмът на войните, където са изобразени сцени от битки и жертвоприношения; храмът на ягуарите, където се намира тронът на владетеля; 
			обсерваторията Каракол, където са правени астрономически наблюдения и стадионът за игра на топка, където се провеждали ритуални състезания с тежка каучукова топка.
			</description>
			<accessibility>
				<transport>
				Чичен Ица се намира на около 200 км от Канкун и на около 120 км от Мерида. 
				Може да се стигне до града с автобус, кола или организирана екскурзия. 
				Автобусите тръгват от автогарите в Канкун и Мерида и отнемат около 2-3 часа. 
				Колата е по-удобен вариант, тъй като позволява да се посетят и други забележителности
				в близост, като карстовия кладенец Икил или града Валядолид. Екскурзиите обикновено 
				включват транспорт, входна такса и водач, но могат да бъдат по-скъпи и по-натоварени.
				</transport>
				<worktime>8:00-17:00</worktime>
				<ticket_price>
				Деца под 13 - безплатно
				Възрастни - 75 лв
				</ticket_price>
			</accessibility>
			<related_landmarks>
				<landmark>
				Карстовия кладенец Икил - естествен извор с кристално чиста вода, който се намира 
				на 3 км от Чичен Ица. Кладенецът е дълбок 40 метра и е обкръжен от тропическа растителност 
				и висящи корени. Може да се плува в него и да се наслаждавате на природната красота на мястото.
				</landmark>
				<landmark>Градът Валядолид - колониален град, който се намира на 40 км от Чичен Ица. Градът 
				има исторически и културен интерес, тъй като е бил сцена на важни събития като Кастовата война. 
				Валядолид притежава красива архитектура, като катедралата Сан Гервасио, манастира Сан Бернардино
				и къщата на Монтейо. Градът е също така близо до други природни и археологически забележителности.
				</landmark>
			</related_landmarks>
			<images>
				<image type="1">
					<image_src href="images/new_wonders/chichen_itza1.jpg" ent="chichen_itza1"/>
				</image>
			</images>
		</wonder>
		
		<wonder wonderId="MACHU_PICCHU">
			<name>Мачу Пикчу</name>
			<nickname>Изгубеният град на инките</nickname>
			<destination>
				<continent>Южна Америка</continent>
				<country>Перу</country>
				<place>Планинска верига, която се извисява над долината Урубамба</place>
				<cont-id>SA</cont-id>
				<type-id>NW</type-id>
			</destination>
			<history>
				<creation>
				Мачу Пикчу е древен град на инките, построен в 15-ти век в Перу.Ето някои интересни факти за историята на Мачу Пикчу:

				- Мачу Пикчу е построен от императора Пачакутек, който разширил и укрепил инкската империя. 
				Той избрал мястото заради неговото стратегическо положение, богатството на водни източници и плодородието на земята.
				- Мачу Пикчу е служил като кралска резиденция, свещен център или убежище за инкските аристократи и свещеници. 
				Там са живели около 750 до 1000 души, които се занимавали със земеделие, ремесла, астрономия и религия.
				- Мачу Пикчу е бил напуснат около 1572 година, след като испанците завладели Перу и унищожили инкската империя. 
				Няма доказателства, че испанците някога са стигнали до града, който останал забравен и скрит в горите.
				Мачу Пикчу е бил "открит" от американския археолог Хайрам Бингам през 1911 година, който търсел последната инкска крепост Вилкабамба. 
				Той бил заведен до града от местен фермер и бил първият западняк, който го е видял. 
				Бингам направил много снимки и изследвания на Мачу Пикчу и го популяризирал в света.
				</creation>
				<changes>
				Части от Мачу Пикчу вече са забранени за туристи заради ерозията в района. 
				Големият брой посетители е причина за влошаване на състоянието на каменните структури в три емблематични части на цитаделата - Храма на кондора, Храма на Слънцето и Интиуатана.
				Ето защо е необходимо те да бъдат затворени за поддръжка. Щетите вече са необратими.
				</changes>
			</history>
			<description>
			Мачу Пикчу е съвременното име на архитектурен комплекс в южната част на днешно Перу, построен от инките през XV век. 
			Той влиза в Списъка на световното културно и природно наследство на ЮНЕСКО от 1983 г.
			Дворците, храмовете и домовете са на 2430 m надморска височина в Андите. 
			Наричан е още „Изгубеният град на инките“. 
			Създаден е като свещена планинска резиденция на великия владетел на инките Пачакути, век преди неговата империя да падне, тоест приблизително към 1440 г.,
			и е функционирал до 1532 г., когато испанците нахлуват в територията на империята. През 1532 г. всичките му жители тайнствено изчезват.
			</description>
			<accessibility>
				<transport>
				Качването отнема около 20 минути. 
				Влакът превозва пътници на всеки 20-30 минути от начална гарата от 8:20 ч. до 17 ч. всеки ден, а последният курс в обратна посока е между 18:30 ч. и 19 ч.
				</transport>
				<worktime>
				От 5:30 ч. до 12:00 ч.
				От 12:00 ч. до 17:30 ч.
				</worktime>
				<ticket_price>
				Вид билет						Цена за чужденци	Цена за Андската общност
				Мачу Пикчу							63 евро						33 евро
				Мачу Пикчу + Хуайна Пикчу			77 евро						47 евро
				Мачу Пикчу + Планина Мачу Пикчу		77 евро						47 евро
				Мачу Пикчу + Музей					69 евро						40 евро
				
				Билетите са ограничени до 2500 на ден и трябва да бъдат резервирани предварително. 
				огат да се купят през официалния сайт на Мачу Пикчу, както и от туроператори. 
				Цената на билета зависи от това, дали искате да влезете само в Мачу Пикчу или искате да включите и други атракции, като Хуайна Пикчу, Планина Мачу Пикчу или Музеят.
				</ticket_price>
			</accessibility>
			<related_landmarks> 
					<landmark>
					Долината на Светите реки (Sacred Valley): Това е областта, през която протичат реките Виликабамба и Урубамба, 
					и където се намират множество инкски развалини и колониални градове.
					</landmark>
					<landmark>
					Озерото Титикака (Lake Titicaca): Най-високото солено езеро в света, което граничи между Перу и Боливия. 
					Околността му предлага прекрасни пейзажи и възможности за изучаване на културата на плуващите острови на Урос.
					</landmark>
					<landmark>
					Град Куско (Cusco): Куско е древен инков град, който служи като стартова точка за посещение на Мачу Пикчу. 
					Градът съчетава индиански и испански архитектурни стилове и е обявен за световно наследство от ЮНЕСКО.
					</landmark> 
			</related_landmarks>
			<images>
				<image type="1">
					<image_src href="images/new_wonders/machu_picchu1.jpg" ent="machu_picchu1"/>
				</image>
			</images>
		</wonder>

		<wonder wonderId="TAJ_MAHAL">
			<name>Тадж Махал</name>
			<nickname>Корона на дворците</nickname>
			<destination>
				<continent>Азия</continent>
				<country>Индия</country>
				<city>Агра</city>
				<cont-id>AS</cont-id>
				<type-id>NW</type-id>
			</destination>
			<history>
				<creation>
				Историята на Тадж Махал започва през 1631 година, когато Мумтаз Махал умира при раждането на четиринадесетото си дете. 
				Шах Джахан, който е безутешен от загубата на любимата си, решава да построи най-великолепния мавзолей в нейна памет. 
				Той избира мястото на брега на река Ямуна, където той и Мумтаз Махал са прекарвали много щастливи моменти.Наема най-добрите архитектори, художници, занаятчии и 
				майстори от цяла Индия, Персия, Османската империя и Европа, за да работят по проекта. Строителството започва през 1632 година и продължава 22 години, 
				като изисква усилията на около 20 000 души и огромни количества материали и ресурси.
				</creation>
				<changes>
				През годините Тадж Махал е претърпял различни промени, които са били повлияни от политически, социални и екологични фактори. Ето някои от тях:

				През 17 век Тадж Махал е бил обект на разбойнически нападения и вандализъм от страна на афгански и персийски войски, които са откраднали и разрушили част от 
				скъпоценните камъни и метали, използвани за украса.
				
				През 18 век Тадж Махал е бил занемарен и запустял от слабите и корумпирани моголски императори, които са загубили контрола над Индия. 
				Той е бил използван като квартира за британски войници и чиновници, които са превърнали градината в английски парк и са разрушили някои от съседните сгради.

				През 19 век Тадж Махал е бил реставриран и консервиран от британската колониална власт, която е възстановила някои от откраднатите и повредените детайли, 
				е премахнала някои от добавените през 18 век елементи и е възвърнала градината в оригиналния си моголски стил.
				
				През 20 и 21 век Тадж Махал е защитаван и поддържан от индийското правителство и различни международни организации, които са се опитали да запазят неговата красота
				и цялост. Създали са зона за защита на околната среда, ограничили са трафика и туризма в близост до паметника и провеждат редовни почиствания и ремонти.

				</changes>
			</history>
			<description>
			Тадж Махал е мавзолей от бял мрамор на южния бряг на река Ямуна в индийския град Агра.
			Комплексът включва още джамия и къща за посетители, както и парк, ограден от три страни с масивна стена. 
			Целият комплекс е напълно завършен към 1653 година, а стойността му е около 32 милиона тогавашни рупии (1,4 милиарда лева от 2015 година). 
			Тадж Махал е обявен за Обект на световното наследство на ЮНЕСКО през 1983 година, като „перлата на ислямското изкуство в Индия и един от срещащите всеобщо възхищение 
			шедьоври на световното наследство. Смятан е за най-добрият образец на моголската архитектура, съчетаваща ислямски, индийски и персийски елементи и за символ на 
			богатата история на Индия. 
			Главната сграда е симетрична и има висок централен купол, около който са разположени четири по-малки купола. 
			Всеки ъгъл на платформата има по едно минаре, което е леко наклонено навън, за да не падне върху мавзолея при земетресение. 
			Входът към комплекса е през голяма арка, която има изписани стихове от Корана. 
			Градината, която окръжава мавзолея, е разделена на четири части, които символизират рая. 
			В центъра на градината тече канал с фонтани, който води до басейн, отразяващ образа на мавзолея.
			Вътрешността на мавзолея е изключително богато украсена с резби, мозайки, флорални мотиви и пиетра дура - техника за вграждане на скъпоценни камъни в мрамора.
			В центъра на мавзолея се намират два кенотафа - символични гробници на Шах Джахан и Мумтаз Махал. 
			Реалните им гробове са разположени под земята, в крипта, която не е достъпна за публиката. 
			</description>
			<accessibility>
				<transport>
				За да стигнете до Тадж Махал, имате няколко възможности за транспорт. 
				Една от тях е да пътувате с поезд от Дели до Агра, където се намира паметникът.
				От станцията Agra Cantonment можете да вземете авто или велорикша, микроавтобус или такси до Тадж Махал. 
				Друга възможност е да пътувате с автобус от Дели до Агра.
				От автогарата можете да вземете същите видове транспорт до паметника. 